### PR TITLE
[feat] disable unstable features

### PR DESCRIPTION
**Pull request by m4dz**

### CODE REVIEW

**Comment by poupotte** [comment]
:+1:

**Comment by flyingrub** [comment]
What was the problem with shuffle ?

**Comment by m4dz** [comment]
@flyingrub neither @poupotte nor me had success to get this feature working when doing som tests. We have just choose to disable it temporarily and get it fixed later.

IMHO, The shuffle should occurs when upnext playlist chose the next title: the player should do a random select in the upNext playlist (rather than selected th next upcoming one), rather than resort the whole upNext playlist.

**Comment by flyingrub** [comment]
It worked well on my side :/
Resort the upNext playlist prevent it to replay the same song twice. It's also like that youtube / soundcloud do.

**Comment by m4dz** [comment]
@flyingrub hmmm, weird… I've just opened an issue about it https://github.com/cozy-labs/cozy-music/issues/53

**Pull request merged**
